spring:
  profiles:
    active:
    - dev
---
server: 
  port: 7003
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-client
---
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---